BENCHNAME=dijkstra_small
BENCHNAME2=dijkstra_large
#ARCH=arm
#MATTR=-mattr=vfp3,d16,a8,-neon -mcpu=cortex-a8 -float-abi=hard

FILE1 = dijkstra_small.c
FILE2 =dijkstra_large.c

TARGETS =dijkstra_small dijkstra_large

SBTOPT?=-optimize -oneregion

include ../../Makefile.common
