BENCHNAME=bitcnts

FILE1 = bitcnts.c bitcnt_1.c bitcnt_2.c bitcnt_3.c bitcnt_4.c bitfiles.c bitstrng.c bstr_i.c 

TARGETS=bitcnts

SBTOPT?=-optimize -oneregion
OPTFLAGS?=-printf-break

include ../../Makefile.common

