all += lrsc_w amoswap_w
all += lrsc_d amoswap_d

all += amoadd_w amoand_w amoor_w amoxor_w amomax_w amomaxu_w amomin_w amominu_w
all += amoadd_d amoand_d amoor_d amoxor_d amomax_d amomaxu_d amomin_d amominu_d

all += zero

include ../common64.mk
