# Immediate load
all = aiupc lui

# Arithmetics
all += add addi addw sub subw
all += and andi or ori xor xori
all += slt slti sltu sltiu

# Control
all += jal jalr
all += beq bne bge bgeu blt bltu

# Load/store
all += lb lw ld lbu lhu lwu
all += sb sw sd

# Shifts
all += sll slli sllw slliw
all += sra srai sraw sraiw srl srli srlw srliw

include ../common64.mk
