BENCHNAME=search_small
BENCHNAME2=search_large

FILE1 = bmhasrch.c  bmhisrch.c  bmhsrch.c  pbmsrch_small.c 
FILE2 = bmhasrch.c  bmhisrch.c  bmhsrch.c  pbmsrch_large.c 

TARGETS=search_small search_large

SBTOPT?=-nolocals
OPTFLAGS=-printf-break

STACKSIZE=400000

include ../../Makefile.common


