# Immediate load
all = aiupc lui

# Arithmetics
all += add addi sub
all += and andi or ori xor xori
all += slt slti sltu sltiu

# Control
all += jal jalr
all += beq bne bge bgeu blt bltu

# Load/store
all += lb lw lbu lhu
all += sb sw

# Shifts
all += sll slli
all += sra srai srl srli

include ../common32.mk
