###
### sbt
###

# debug

SBT_DEBUG_BUILD := $(BUILD_DIR)/sbt/debug
SBT_DEBUG_MAKEFILE := $(SBT_DEBUG_BUILD)/Makefile
SBT_DEBUG_OUT := $(SBT_DEBUG_BUILD)/riscv-sbt
SBT_DEBUG_TOOLCHAIN := $(TOOLCHAIN_DEBUG)/bin/riscv-sbt
SBT_DEBUG_CONFIGURE := \
    $(CMAKE) -DCMAKE_BUILD_TYPE=Debug \
             -DCMAKE_INSTALL_PREFIX=$(TOOLCHAIN_DEBUG) \
             $(TOPDIR)/sbt
SBT_DEBUG_ALIAS := sbt-debug
SBT_DEBUG_DEPS := $(LOWRISC_LLVM_DEBUG_TOOLCHAIN)

# release

SBT_RELEASE_BUILD := $(BUILD_DIR)/sbt/release
SBT_RELEASE_MAKEFILE := $(SBT_RELEASE_BUILD)/Makefile
SBT_RELEASE_OUT := $(SBT_RELEASE_BUILD)/riscv-sbt
SBT_RELEASE_TOOLCHAIN := $(TOOLCHAIN_RELEASE)/bin/riscv-sbt
SBT_RELEASE_CONFIGURE := \
    $(CMAKE) -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_INSTALL_PREFIX=$(TOOLCHAIN_RELEASE) \
             $(TOPDIR)/sbt
SBT_RELEASE_ALIAS := sbt-release
SBT_RELEASE_DEPS := $(RISCV_LLVM_RELEASE_TOOLCHAIN) $(LLVM_RELEASE_TOOLCHAIN)

.PHONY: sbt
sbt: $(SBT)-build $(SBT)-install

