BENCHNAME=susan
#ARCH=arm
#MATTR=-mattr=vfp3,d16,a8,-neon -mcpu=cortex-a8 -float-abi=hard
FILE1 = susan.c

TARGETS=susan

SBTOPT?=-optimize -abi-locals

STACKSIZE=400000

include ../../Makefile.common


